version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    depends_on:
     - redis
  redis:
    image: redis
    
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    links: 
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  spark:
    image: sequenceiq/spark:1.6.0
    command: bash
    volumes:
      - ./target/scala-2.10:/app
    links:
    - kafka